exports.stringArray = [
    `Do you want to know what I love? \n
    Fucking beautiful women. Making them cum by only saying "Take off your clothes.". Being their master. Being their man. \n
    I also love being the best in everything I do. And, indeed, I am the best at everything I do. Great job, huge levels of intelligence, great body, respected by everyone and being the dream of every woman of this planet.\n
    In conclusion, I love everything about my life. What do you love? \n
    NOTHING. Because you are still living in the caves. Everything you think you love is a LIE.`,
    `My girlfriend is cute and smart and she's an anime faggot like me \n
    The other night she and I were cuddling in bed and she started humping me and whispering "oniichan oniichan" and that turned me the fuck on \n
    so I called her "oneechan" and then she stopped and looked at me and I said "what is it" to which she replied "I always wanted a twin brother so we could fuck all the time" (she's an only child and all I have is a younger brother) \n
    so all night long we were humping and calling each other oniichan and oneechan and I came in my underwear and we were pretending we were brother and sister trying to sexually please each other without having sex and it was fucking hot`,
    `Want to know what Anime really means? \n
    A is for Appalling, just like those "Hen Tie" games.\n
    N is for Nefarious, as anime is made by the devil.\n
    I is for Immoral - Anime fans are 60% more likely to commit rapes!\n
    M is for Meticulous, because anime slowly chips away at your morality.\n
    E is for Evil - so stay away from anime!!`,
    `i love Japanese girls and Chinese girls and all so Vietnamese girls Korean girls Taiwanese girls Filipino girls Cambodian girls Indonesian girls Malaysian girls i love all the Asian girls they are so sexy and cute and beautiful and so adorable i want a Asian girl to be my wife and me and her will love each other for ever and i would do anything for her i would do all the stuff that needs to be done around the house and she could just relax and chill and i would all ways give her gas money for when she drives me around i would all ways make sure she has a full tank of gas in her car and i would protect her with my life i would even take a bullet from a gun for her and make sure she is alive and well and i would give her give her massages every day when she is sleepy from work and all so she could boss me around and tell me what to do cause i would be her man her property i would do anything for a Asian girl who wants to be my wifey or my girl friend`,
    `uuuh this has been bothering me for a while wow um i cant believe im getting this of my chest the thing is just like transexuals feel they were born the wrong gender i feel like i was born the wrong mental state as a non autistic person \n
    i have taken many online tests and i always score incredibly low on the autism scale but on the inside i feel like i am true autist`,
    `Im looking for a bento box, it cant be pinku (thats japanese for pink) or any girl color. It has to be of 2 or more kotoba (thats japanese for 2 compartments) and has be be chibi (small) sized. And has to be really kawaii (cute). Also It has to be about 10-20 bux. And you have to post pics of it first (i want to make shure it's kawaii [cute]). And it would be nice if it came with matching chopstick holder (WITH chopsticks). OH! and it CANNOT have any cartoon pictures, or be made out of plastic. It has to be made of ceramic, or something like that. Also it would be nice if it was made in japan. and not in china or corea (korea) or whatever. I have found a bento box similar to the one im describing in e-bay, but it was 1 kotoba, and i dont want my gohan (rice) to touch my other things (it can get wet and i would not like that, plus 2 compartments looks more kawaii`,
    `So I hear that some people believe that being a brony is gay. I told Pyro, Sparkup, and Merlin this. They didn't like what I said. People should know that not only are us bronies artistic, some bronies are in the military, trained to kill. Some of us, like me, also have very sharp katanas lying around. So, if you have a problem with the idea of older people watching My Little Pony Friendship is Magic, this sword is ready.`,
    `has anybody seen my cat around here ive been looking for it for years but it just seems to be a dead baby every time i get close to tracking it down please help she looks similar to my washing machine if you dont know what it looks like it big white and black`,
    `sɪᴛᴛɪɴɢ ɪɴ ɴɪᴘᴘᴏɴ ᴄʟᴀss, ɪ sᴛᴀʀᴇ ᴅᴏᴡɴ ᴛᴇᴀᴄʜᴇʀ. sʜᴇ sᴀʏ ᴛʜᴇ ᴊᴀᴘᴀɴᴇsᴇ ʜᴏᴡ ɪ ʟɪᴋᴇ. ᴀᴛ ʟᴀsᴛ sʜᴇ sᴀʏs ᴛʜᴇ ᴛʀɪɢɢᴇʀ "Cᴏᴏᴋɪᴇ". ɪ ғᴜʀɪᴏᴜsʟʏ ᴄʜᴀʀɢᴇ ᴏᴜᴛ ᴏғ ᴍʏ sᴇᴀᴛ, ᴄᴀᴛᴄʜɪɴɢ ʜᴇʀ ᴡɪᴛʜ ᴍʏ 5ᴘᴄ ʀᴀᴇᴋᴏʀs. sᴛᴜɴɴᴇᴅ ɪɴ ғʀᴏɴᴛ, ʀᴀᴍᴍᴇᴅ ɪɴғɪᴛᴇ ᴛɪᴍᴇs. ɪ ɢᴇᴛ ᴍʏ ᴄᴏᴏᴋɪᴇ.`,
    `Due to extensive research done by the University of Pittsburgh, diamond has been confirmed as the hardest metal known to man. The research is as follows. Pocket-protected scientists built a wall of iron and crashed a diamond car into it at 400 miles per hour, and the car was unharmed.\n
    They then built a wall out of diamond and crashed a car made of iron moving at 400 miles an hour into the wall, and the wall came out fine. They then crashed a diamond car made of 400 miles per hour into  a wall, and there were no survivors. \n
    They crashed 400 miles per hour into a diamond travelling at iron car. Western New York was powerless for hours. They rammed a wall of metal into a 400 mile per hour made of diamond, and the resulting explosion shifted the earth's orbit 400 million miles away from the sun, saving the earth from a meteor the size of a small Washington suburb that was hurling towards mid-western Prussia at 400 billion miles per hour.\n
    They shot a diamond made of iron at a car moving at 400 walls per hour, and as a result caused over 9000 wayward air planes to lose track of their bearings, and make a fatal crash with over 9000 buildings in down town New York. They spun 400 miles at diamond into iron per wall. The results were inconclusive. \n
    Finally, they placed 400 diamonds per hour in front of a car made of wall travelling at miles per iron, and the result proved without a doubt that diamonds were the hardest metal of all time, if not just the hardest metal known to man.\n`,
    `Listen here cum-slut, I bet you 5 million dollars that you don’t own a bird. But guess what? I own 7. And I can tell you right now that a bird would never just walk into something like a chocolate fountain. They’ll rarely walk directly into water. But say that your idiotic theory is correct.Say it did actually walk into it.That animal still probably died.Is that still funny to you? Do you still get your kicks out of knowing that that bird was probably terrified and opening its mouth to scream in that last panel?And if you say yes then you seriously disgust me as a human being.`,
    `I flexed My bulging, huge, muscles ripped my shirt off, and six women lined up. We had an orgy, which didn't last too long. Each woman climaxed when my dick came within five inches of her VAGINA, and went into an eternal state of euphoria after I put it in. I came, and three hundred gallons of semen shot out. It landed in Ghana, and ended the drought.`,
    `i rammed a 16 GB asian kid down my ear to calculate the toll of the toll booth and he violently shook and pissed all over himself. in desperate need of another asian i went to the closest source of asians. an ivy league school or a tibetan community. both ends of the spectrums really. im so high. do dogs know when they're pregnant or do they kinda shit a litter of puppies and freak the fuck out "lol wtf ius comin out my ass"`,
    `Yes, I am a fox. So? I dont see any problem. I embraced my animal soul long ago and I am happy together with my boyfriend (who is a cute b/w wolf!). We have a fucking lot of friends in and outside of the fandom and I am pretty slim and good looking. \n
    But thanks anyway asshole. Go and watch your stupid anime shit while I have SEX with my boyfriend.`,
    `My Grandfather smoked his whole life. I was about 10 years old when my mother said to him, 'If you ever want to see your grandchildren graduate, you have to stop immediately.'. Tears welled up in his eyes when he realized what exactly was at stake. He gave it up immediately. Three years later he died of lung cancer. It was really sad and destroyed me. My mother said to me- 'Don't ever smoke. Please don't put your family through what your Grandfather put us through." I agreed. At 28, I have never touched a cigarette. I must say, I feel a very slight sense of regret for never having done it, because your post gave me cancer anyway.`,
    `I sexually Identify as an Attack Helicopter. Ever since I was a boy I dreamed of soaring over the oilfields dropping hot sticky loads on disgusting foreigners. People say to me that a person being a helicopter is Impossible and I'm fucking retarded but I don't care, I'm beautiful. I'm having a plastic surgeon install rotary blades, 30 mm cannons and AMG-114 Hellfire missiles on my body. From now on I want you guys to call me "Apache" and respect my right to kill from above and kill needlessly. If you can't accept me you're a heliphobe and need to check your vehicle privilege. Thank you for being so understanding.`,
    `why? because i party and u dont ;) for ur information i get a lot of pussy. more then you could ever think of HAHAHAA ;) so before you downvote me make sure you know who you are talking too ;) because they might be better then you at some stuff like getting pussy and head. I got to go my girlfriend is calling right now she wants to know if i want to have sex with her ;) i bet you dont even have a girlfriend pussy ;) i bet you have a boyfriend or something ;) HAHA well toodaloo and guess what teenagers sex isnt hard to get.. you just got to try hard enough and you will get sex. sex is amazing pce pussy ;)`,
    `hi every1 im new!!!!!!! *holds up spork* my name is katy but u can call me t3h PeNgU1N oF d00m!!!!!!!! lol…as u can see im very random!!!! thats why i came here, 2 meet random ppl like me _… im 13 years old (im mature 4 my age tho!!) i like 2 watch invader zim w/ my girlfreind (im bi if u dont like it deal w/it) its our favorite tv show!!! bcuz its SOOOO random!!!! shes random 2 of course but i want 2 meet more random ppl =) like they say the more the merrier!!!! lol…neways i hope 2 make alot of freinds here so give me lots of commentses!!!! \n
    DOOOOOMMMM!!!!!!!!!!!!!!!! <--- me bein random again _^ hehe…toodles!!!!! \n
    love and waffles, \n
    t3h PeNgU1N oF d00m`,
    `ﾉ◕ヮ◕)ﾉ:･ﾟ KAWAII WAVE!!:„ø¤º°¨ ¨°º¤KEEP THE KAWAII GOING ¸„ø¤º°¨ ¨°º¤øº LETS GO KAWAII !¤¤º°¨¨°º¤øº¤ø„¸¸ø¤º°¨„ ø¤º°¨¨°ºL-E-T-S GO!„ø¤º°¨ ¨°º¤LET'S GO KAWAII !¸„ø¤º°¨¨°º¤øºL-E-T-S GO!¤¤º°¨ ¨°¤øº¤ø„¸¸ø¤º°¨LET'S GO KAWAII :„ø¤º°¨¨°º¤KEEP THE WAVE GOING •ᴥ•¸„ø¤ºﾉ◕ヮ◕)ﾉ:･ﾟ KAWAII WAVE!!:„ø¤º°¨ ¨°º¤KEEP THE KAWAII GOING ¸„ø¤º°¨ ¨°º¤øº LETS GO KAWAII !¤¤º°¨¨°º¤øº¤ø„¸¸ø¤º°¨„ ø¤º°¨¨°ºL-E-T-S GO!„ø¤º°¨ ¨°º¤LET'S GO KAWAII !¸„ø¤º°¨¨°º¤øºL-E-T-S GO!¤¤º°¨ ¨°¤øº¤ø„¸¸ø¤º°¨LET'S GO KAWAII :„ø¤º°¨¨°º¤KEEP THE WAVE GOING •ᴥ•¸„ø¤ºﾉ◕ヮ◕)ﾉ:･ﾟ KAWAII WAVE!!:„ø¤º°¨ ¨°º¤KEEP THE KAWAII GOING ¸„ø¤º°¨ ¨°º¤øº LETS GO KAWAII !¤¤º°¨¨°º¤øº¤ø„¸¸ø¤º°¨„ ø¤º°¨¨°ºL-E-T-S GO!„ø¤º°¨ ¨°º¤LET'S GO KAWAII !¸„ø¤º°¨¨°º¤øºL-E-T-S GO!¤¤º°¨ ¨°¤øº¤ø„¸¸ø¤º°¨LET'S GO KAWAII :„ø¤º°¨¨°º¤KEEP THE WAVE GOING •ᴥ•¸„ø¤º ﾉ◕ヮ◕)ﾉ:･ﾟ KAWAII WAVE!!:„ø¤º°¨ ¨°º¤KEEP THE KAWAII GOING ¸„ø¤º°¨ ¨°º¤øº LETS GO KAWAII !¤¤º°¨¨°º¤øº¤ø„¸¸ø¤º°¨„ ø¤º°¨¨°ºL-E-T-S GO!„ø¤º°¨ ¨°º¤LET'S GO KAWAII !¸„ø¤º°¨¨°º¤øºL-E-T-S GO!¤¤º°¨ ¨°¤øº¤ø„¸¸ø¤º°¨LET'S GO KAWAII`,
    `HEY KISAMAS, \n
    WATASHI NO NAMAE WA ANANIMASU OFFU KAKUSU TO WATASHI WA KIRAI EVERY SINGLE ONE OF ANATA. ALL OF ANATA ARE FAT, BAKA BAKA NO-LIFES WHO SPEND EVERY SECOND OF MAINICHI MITEIRUING AT BAKA PICTURES. ANATA WA SUBETE THAT IS WARUI IN THE SEKAI. HONTO NI, HAVE ANY OF ANATA EVER GOTTEN ANY NEKO? I MEAN, WATASHI GUESS IT'S TANOSHI MAKING FUN OF HITOS BECAUSE OF YOUR OWN UNKAWAIINESS, BUT MINNA TAKE IT TO A WHOLE NEW LEVEL. KORE WA WORSE THAN ONANI-ING TO PICTURES ON HESUBUUKU. \n
    SHIRANAI HITO JA NAI DESHO? JUST HIT WATASHI AND BE SURE TO GANBARIMASU. WATASHI WA PRETTY MUCH PAAFEKUTO. WATASHI WAS AMERIKAN FUTBORU NO CAPTAIN, TO WATASHI WAS HAJIMASHTATER ON WATASHI NO BASUKETOBOORU TEAM. DONNA SUPOTSU DO ANATA ASANBOU, OTHER THAN "ONANI TO NAKED DRAWN NIPPONJIN"? WATASHI MO GET HOMO JA NAI A'S, TO WATASHI HAS A BANGING KAWAII SHOJO (KANOJO WA BLOWJOB WO SHIMASHITA; KUSO WA HONTO NI CASH.) ANATA WA ALL KISAMAS DARE SHOULD JUST KOROSU THEMSELVES. DOMO ARIGATOU GOZAIMASU FOR LISTENING.\n
    (SONO PIC WA RELATED DESU, ARE WA WATASHI TO WATASHI NO ONNA)`,
    `I will never fold under this endless barrage of insults on MY person, against MY children and against MY god. I have been fighting this disease since Pokemon in the 90's and I have no intention of stopping becausse of some devil-worshiping "otaku" who combine brainless rhetoric about how much anime has "helped" them become better people, with cure words and display pictures containing fetishised young women they like to call "lolly".`,
    `ok for one, "meow" is literally my catphrase (see what i did there?) whenever someone says "meow" on fb or something, i respond "HEY! that's MY catphrase" thing 2... i was so depressed at one point in my life that i tried to put myself into a coma by drinking too much water. it involved me watching too much robot chicken, and drinking from 3 full big glasses of water over and over without hardly stopping. i dont think it worked though because i urinated too much. good source of water though! ;D`,
    `Hello Everybody, my name is Moursi Fanshawe. I would like to take this time to thank a really good friend of mine and my mentor; a real nice guy called 'hr'. I would really love if one day I could play as well as him. \n
    hey im moursi and i would like to thank my mentor hr for teaching me how to be a good scout, i hope one day to be as good as him \n
    hey im forsak3n and i would like to thank my mentor konr ︻デ┳═ー for teaching me how to be a good sniper, i hope one day to be as good as him`,
    `What the darn-diddily-doodily did you just say about me, you little witcharooney? I’ll have you know I graduated top of my class at Springfield Bible College, and I’ve been involved in numerous secret mission trips in Capital City, and I have over 300 confirmed baptisms. I am trained in the Old Testament and I’m the top converter in the entire church mission group. You are nothing to me but just another heathen. I will cast your sins out with precision the likes of which has never been seen before in Heaven, mark my diddily-iddilly words. You think you can get away with saying that blasphemy to me over the Internet? Think again, friendarino. As we speak I am contacting my secret network of evangelists across Springfield and your IP is being traced by God right now so you better prepare for the storm, maggorino. The storm that wipes out the diddily little thing you call your life of sin. You’re going to Church, kiddily-widdily. Jesus can be anywhere, anytime, and he can turn you to the Gospel in over infinity ways, and that’s just with his bare hands. Not only am I extensively trained in preaching to nonbelievers, but I have access to the entire dang- diddily Bible collection of the Springfield Bible College and I will use it to its full extent to wipe your sins away off the face of the continent, you diddily-doo satan-worshipper. If only you could have known what holy retribution your little “clever” comment was about to bring down upon you from the Heavens, maybe you would have held your darn-diddily-fundgearoo tongue. But you couldn’t, you didn’t, and now you’re clean of all your sins, you widdillo-skiddily neighborino. I will sing hymns of praise all over you and you will drown in the love of Christ. You’re farn-foodily- flank-fiddily reborn, kiddo-diddily.`,
    `Tʜᴇ ᴘʜᴏɴᴇ ʀɪɴɢs. "Hᴇs sᴛɪʟʟ ᴅᴏɪɴɢ ᴛ6 sɪʀ". Mʏ ᴏʀᴇᴏ ʜᴀᴍʙᴜʀɢᴇʀ ғᴀʟʟs ᴛᴏ ᴛʜᴇ ғʟᴏᴏʀ. "REMOVE IT ALL, IM COMING BACK". Jᴀʏ Wɪʟsᴏɴ ʀᴇᴛᴜʀɴs ᴀs ʜᴇᴀᴅ ᴏғ ᴅɪᴀʙʟᴏ. ᴀʟʟ ɪᴛᴇᴍs ʀᴇᴍᴏᴠᴇᴅ ғʀᴏᴍ ɢᴀᴍᴇ. ᴛʜᴇ ᴅᴀʀᴋ ᴀɢᴇ ɪs ᴜᴘᴏɴ ᴜs.`,
    `Omg hai ^ I'm Ai-san and I absolutely luuuv 88 anime <3 and my fav is naruto!!! Okies so anyways, im going to tell you about the BEST day of my life when I met my hot husband sasuke!! <333333333 OMFGZ HE WAS SOOOOO FREAKIN KAWAII IN PERSON!!! Supa kawaii desu!!!!!!!!! ^______________^ When I walked onto Tokyo street ==I looked up and saw...SASUKE!!!!!!!!! <33333333333333333333333333333333333!!!! * KONNICHIWAS OMGZZZZZZZZZZZZZZZZZZZ SUPA SUPA SUPA KAWAII SASUKE-SAMA!!!!!* I yelled n___n then he turned chibi then un-chibi!! he looked at me [O.O;;;;;;;;;;;;;;;;;;;;;;] and then he saw how hot I am *____* he grabbed my hand and winked ~_^ then pulled me behind a pocky shop o_o and started to kiss me!!!!! [OMG!!!! HIS TOUNGE TASTED LIKE RAMEN!!! RLY!!! >.> <.< >.< (0) (0) (0)] then I saw some baka fat bitch watching us and I could tell she was undressing him with her eyes!!!!!!! -____-;;;;;; OMG I COULDN'T BELIEVE IT EITHER!!! (ò_ò) (ò_ò) (ò_ò) so I yelled UH UH BAKA NEKO THAT'S MY MAN WHY DON'T YOU GO HOOK UP WITH NARUTO CAUSE SASUKE-SAMA LOVES ME!!! (ò_ò) then sasuke held me close == and said he would only ever love me and kissed me again!!! (O)/ then we went to his apartment and banged all night long and made 42 babies and they all became ninjas!!!!!!!!!!!!! Nyaaaaa!!!! (^__<)`,
    `Hello m'lady, how are you on this fine day? *kisses your hand* I'll have you know that i'm not your usual stereotipical guy, to be honest i'll be the one in the kitchen, I actually treat girls with respect(but those dumb sluts can't see it and they date some fucking douchebags anyway).I was hoping we could get togheter and have dinner, i'll pick you up and we can ride on my scooter and we can go to McDonalds(i know where you live don't worry).I have alredy sent you a funny meme about us beeing togheter, i will see you soon my soon to be wife *tips fedora in a sensual way*`,
    `It was a hot summer day and I was in my workout room benching 1200 pounds. My abs were flexing and girls within a 10 mile radius were getting wet. Once I was done with my daily 32 hour workout I called one of the bitches I know. She is really damn hot and looks like a supermodel. SO I got into my Lamborghini and revved it up to 40,000 RPM (this is an Italian import with special engine system). I got onto the freeway near my house and threw it into 8th gear, I hit about 600 mph and I could hear the sonic boom as I broke the sound barrier. As I was flooring it on the freeway like a badass, she called me and said she wanted me to **** her. So be it. \n
    I came to a full stop from 700 mph in front of her house. These Ferraris have top notch brakes, you know. So she gets out of the house and walks up to my Bugatti and starts eyeballing my dick. I could tell she was staring at it because when I looked at her I noticed she was looking at my dick. Booya. \n
    Flash forward 10 minutes later. My 30 inch dick is going inside of her VAGINA, hitting them walls. I'm holding her entire body up with my left pinky as I'm ****ing her and she has 30 orgasms. She looks me in the eyes and she says "harder." V-TEC just kicked in, yo. I blow my load so hard she falls off my dick. There had to have been about two pints of cum everywhere. People say I cum like a pornstar, I wouldn't disagree with them. \n
    I throw her a towel so she can clean herself up then I do a triple backflip into my Maserati and drive home`,
    `fuck girl she fuck dick good thank-you hahahaha sixty-nine fuck. \n
    you sexy snake nigger bitch cunt badger geese hand-beezy fuck.\n
    crusty dingleberry juice subway tastes fresh yes-please AAAA t-nigs t-nigs.\n
    superfluous cum in woman hole mmmm thank-you. \n
    goodbye virginity cant even exist asshole.\n
    ku$h blazin' krew hand-beezy cheezy squad roll of nignog.\n
    pu$$y flesh. \n
    cummies boipussy dank finger-lickin' vapes.\n
    fedora tipped, dick dipped, neckbeard itchy, ainsley bitchy, destruction.\n
    spread eagle, open vaginal-area enflamed, japs-eye poonani-pound hound.\n
    parallelogram slanted cock into fuckboy's. \n
    coco-nips inserted anally indoctrinate the group of twinks. \n
    bumming muzzers (as in muslims) fresh milk from cow starting to leak ellipsis (...)`,
    `I sexually Identify as a steel beam. Ever since 9/11 I dreamed of getting drawn closer and closer to my melting point by jet fuel under the Twin Tower letting them drop on disgusting foreigners. People say to me that a person being a steel beam is Impossible and I’m fucking retarded but I don’t care, I’m beautiful. I’m having a plastic surgeon install steel beams and jet fuel on my body. From now on I want you guys to call me “Steel Beam” and respect my right to not melt by jet fuel and kill needlessly. If you can’t accept me you’re a steeliphobe and need to check your metallic privilege. Thank you for being so understanding.`,
    `I recently switched to porn. It's free and you can watch as long as you like because there are literally BILLIONS of video's out there. \n
    I try to fap as much as possible - as hardcore as possible. My current record is 16 faps a day. You have to min/max your sperm loads to get the max faps a day. \n
    I really try hard to get to 20. I have a brainstorm session everyday with several other people including Eddy Pasterino. He gave me some really interesting tactics, which I can't share here unfortunately...`,
    `suck my black cock you tryhard faggot techies noob, fucjking imbecil mongoloid ruinse whole game wasting our time like fucking mongoloid fucking piece of cunt fuck you and your mother in the ass, i hope your mother gets raped by 20 niggers in the ass while they force you to lick their cum dripping down from your mothers asshole you low rated piece of cunt`,
    ` I've never had sex with a girl, because I don't know how to pick them up. That's why I turned Furry. But now I'm just tired of guys ripping my *** when they don't use lubrication. I've had to get stitches three times. I went out with a fox last night who said he only gives, he doesn't receive, so I had to suck his dick and he made me swallow or he would kick my ***.`,
    `I hate weeaboos. I don't conisder myself a weeaboo, I'm actually Japanese for real, well almost. I will be when I live in Japan though. Right now I'm studying japanese, japanese history and I'm following Bushido, the way of the warrior. This is why I hate weeaboos that know 5 words in japanese and use them all the time, kawaai baka DESU NE MOTHERFUCKER. I'm actually trying to become Japanese for real unlike all these faker wees. FUCK YOU WEEABOOS`,
    `Woke up this morning 5:30 sharp with a blowjob from two bitches, one was trying to fit my humongous 3 pound balls in her mouth while the other was choking halfway on my 18 and 3/8 inch dick. Must have came about a quart of sperm. They wanted more, cockslapped them unconcious, I had to hit the gym. Frontflipped from my 14th floor loft into my valet parked 2012 Ferrari (I got connexions) and gave the valet 3000$ in loose change. Pushed my **** to about 4 hundo (mph, mind you) and I was at the gym in no time. When I entered, the room scent suddently changed from sweat to wet pussy. That;s just the effect I have on hoes. Did my usual relax routine, 6000 push-ups, 8500 crunches, bench pressed 30 plates, etc. etc. you know the drill. After doing my **** in 16 minutes, my super strong senses got in action, I was smelling pussy. I looked up, and sure enough this fly honey was coming towards me. When i say fly, I mean that bitch was fine as a ****ing umbrella. 18 years old, 44DD titties on a tight ****ing frame. I mean a real skinny bitch, the type you losers jack off to, she didnt weigh more than 5 pounds. Took out my trouser monster and she started to squirt hard, she was convulsing and having 6 orgasms at the same time. Then I gave it to her while all the guys were giving me high fives and all the hoes were on the floor squirting like mother****ing fountains. Made the **** beg for my cum, but I didnt give it to her to prove a point, I still came but only compressed air came out, imagine your best orgasm, then multiply it by 35. Didnt say nothing, hopped back in the Lambo and went back home. Now I'm sitting here, drinking 15 000$ champagne and eating gold plated sushis made by the 2 bitches from earlier. Its only 6:30 and I did more in 1 hour than you ***gots will do your whole life. Enjoy jacking off to stupid drawn pictures.`,
    `Well, i always loved and was obsessed with wolves as soon as i found out about them as a little child, i actually tried to relate to one any way possible. Not very long after that i found out about a werewolf, And they became a passion along with wolves, because they were just so awesome! And i even acted like one and wanted to be a werewolf, so word got around and i became wolf boy...I even cut my nails like claws. xD So as i grew up i still loved and was obsessed with a werewolf and wolves, but i always felt like something was missing. Can i turn into a wolf and not kill everyone? i want to be a nice wolf haha. Thats what i always said. Getting into teen years i was on the internet alot more, and i decided one day, that there has to be more people out there who love wolves as much as i do, that want to act like one or dress up even. So i researched and looked around eventually finding something called...The furry fandom. At first it sounded and looked cute and funny, but i wasnt actually noticing that these people are just like me, this is that missing part in my life. After looking a bit i finally got into researching the fandom, realizing these people are exactly like me, but surprised me more was seeing other anthro animals, i had only seen a werewolf before and now this. It was pretty awesome and i finally felt good, because i knew then i wasnt alone. From that very day i have made my fursona and alot more friends, learning new things and hopeing to get a fursuit one day. ^.^ Anthropomorphics is what i was searching for, and i couldnt word it. And i know now im a furry. :P `
    ];